<?php

/**
 * @var \Solteq\TranslationManagement\Block\Index $block
 */
$languageFiles = $block->findLanguageFiles();
?>
<html>
<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 40%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-name{width:30%}
    .post-edit{width:10%}
    .csv-field{border: none; width: 100%; background: none;}

</style>
<body>
    <?php
    $currentFile;
    if (isset($_POST['lang_file'])) {
        $currentFile = $_POST['lang_file'];
    }

    if (isset($_POST['editedArray'])) {
        //$block->saveLanguageFile($_POST['editedArray'], '/var/www/helloworld/app/code/Mageplaza/HelloWorld/i18n/hu_HU.csv');
        echo $block->saveLanguageFile($_POST['editedArray'], $_POST['lang_file']);
    }

    // .csv file editor layout
    if (isset($_POST['lang_file'])) {
        $langArray = $block->openLanguageFile($_POST['lang_file']);
        if ($langArray !== 'error') {
            echo '
            <a href=\'?\'><button>Go back</button> </a>
            <form method="post" action="">
            <table id="editable_table">
                <tr>
                    <th>String</th>
                    <th>Translation</th>
                </tr>
                <tr>';
            for($i=0;$i<count($langArray);$i++){
                echo '
                    <td><input class="csv-field" type="text" name="editedArray['.$i.'][0]" value="'.$langArray[$i][0].'"></td>
                    <td><input class="csv-field" type="text" name="editedArray['.$i.'][1]" value="'.$langArray[$i][1].'"></td>
                </tr>';
            }
            echo '
            </table>
            <input type="hidden" name="form_key" value="'.$block->getFormKey().'" />
            <input type="hidden" name="lang_file" value="'.$currentFile.'" />
            <input type="submit" value="Submit">
            </form>';
        }
    }
    // .csv file list layout
    else {
        echo '
        <table>
            <tr>
                <th class="post-name">Name</th>
                <th class="post-edit">Content</th>
               </tr>
            <tr>';
        foreach ($languageFiles as $language){
            echo '
                <td>'.$language.'</td>
                <td>
                    <form method="post" action="">
                        <input type="hidden" name="lang_file" value="'.$language.'">
                        <input type="hidden" name="form_key" value="'.$block->getFormKey().'" />
                        <input type="submit" value="Edit">
                    </form>
                    <!-- <a href=\'?file='.$language.'\'><button>Edit</button> </a> -->
                </td>
            </tr>';
        }
        echo '</table>';
    }
    ?>
</body>
</html>
