<?php

/**
 * @var \Solteq\TranslationManagement\Block\Index $block
 */
$languageFiles = $block->findLanguageFiles();
?>
<html>
<style>

    strong {
        font-weight: bold;
    }

    em {
        font-style: italic;
    }

    table {
        background: #f5f5f5;
        border-collapse: separate;
        box-shadow: inset 0 1px 0 #fff;
        font-size: 12px;
        line-height: 24px;
        margin: 30px auto;
        text-align: left;
        width: 800px;
    }

    th {
        background: linear-gradient(#777, #444);
        border-left: 1px solid #555;
        border-right: 1px solid #777;
        border-top: 1px solid #555;
        border-bottom: 1px solid #333;
        box-shadow: inset 0 1px 0 #999;
        color: #fff;
        font-weight: bold;
        padding: 10px 15px;
        position: relative;
        text-shadow: 0 1px 0 #000;
    }

    th:after {
        background: linear-gradient(rgba(255,255,255,0), rgba(255,255,255,.08));
        content: '';
        display: block;
        height: 25%;
        left: 0;
        margin: 1px 0 0 0;
        position: absolute;
        top: 25%;
        width: 100%;
    }

    th:first-child {
        border-left: 1px solid #777;
        box-shadow: inset 1px 1px 0 #999;
    }

    th:last-child {
        box-shadow: inset -1px 1px 0 #999;
    }

    td {
        border-right: 1px solid #fff;
        border-left: 1px solid #e8e8e8;
        border-top: 1px solid #fff;
        border-bottom: 1px solid #e8e8e8;
        padding: 10px 15px;
        position: relative;
        transition: all 300ms;
    }

    td:first-child {
        box-shadow: inset 1px 0 0 #fff;
    }

    td:last-child {
        border-right: 1px solid #e8e8e8;
        box-shadow: inset -1px 0 0 #fff;
    }

    tr {

    }

    tr:nth-child(odd) td {
        background: #f1f1f1;
    }

    tr:last-of-type td {
        box-shadow: inset 0 -1px 0 #fff;
    }

    tr:last-of-type td:first-child {
        box-shadow: inset 1px -1px 0 #fff;
    }

    tr:last-of-type td:last-child {
        box-shadow: inset -1px -1px 0 #fff;
    }

    tbody:hover tr:hover td {
        background: #E4F7FE;
    }

    .sticky {
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        padding: 50px;
        font-size: 20px;
        z-index:10;
    }


    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-name{width:30%}
    .post-edit{width:10%}
    .csv-field{border: none; width: 100%; background: none;}
</style>

<body>

    <?php
    //.csv-field{border: none; width: 100%; background: none;}
    $currentFile;
    if (isset($_POST['lang_file'])) {
        $currentFile = $_POST['lang_file'];
    }

    if (isset($_POST['editedArray'])) {
        $block->saveLanguageFile($_POST['editedArray'], $_POST['lang_file']);
    }

    // .csv file editor layout
    if (isset($_POST['lang_file'])) {
        $langArray = $block->openLanguageFile($_POST['lang_file']);
        if ($langArray !== 'error') {
            echo '
            
            
            <div class="page-main-actions sticky">
                <div class="page-actions-placeholder"></div>
                    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                        <div class="page-actions-inner" data-title="Edit translations">
                        
                            <form method="post" action="">
                                <select name="lang_file" onchange="this.form.submit()">
                                <option value="">'.$currentFile.'</option>';
                                    foreach ($languageFiles as $language) {
                                        echo '
                                            <option value="'.$language.'">'.$language.'</option>';
                                    }
                                echo '  
                                </select>
                                <input type="hidden" name="form_key" value="' . $block->getFormKey() . '" />
                            </form>
                             
                            <div class="page-actions-buttons">
                                
                                <button id="back" type="button" class="action-default scalable back" data-ui-id="attribute-edit-content-back-button" onclick="location.href=\'?\'">
                                    <span>Back</span>
                                </button>
                                <form method="post" action="">
                                <button id="save" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Save Attribute" type="submit" data-ui-id="attribute-edit-content-save-button" role="button" aria-disabled="false">
                                    <span class="ui-button-text">
                                        <!-- <input type="submit" value="Submit"> -->Save
                                    </span>
                                </button>
                                
                                <button value="langTable" onclick="addRow()" id="new_line" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="New Line" type="button" data-ui-id="attribute-edit-content-save-button" role="button" aria-disabled="false">
                                    <span class="ui-button-text">
                                        <span>New Line</span>
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <!-- <a href=\'?\'><button>Go back</button> </a> -->
            
            <table id="editable_table">
                <tr>
                    <th>String</th>
                    <th>Translation</th>
                </tr>
                <tr>';
            for($i=0;$i<count($langArray);$i++){
                echo '
                    <td><input class="csv-field" type="text" name="editedArray['.$i.'][0]" value="'.$langArray[$i][0].'"></td>
                    <td><input class="csv-field" type="text" name="editedArray['.$i.'][1]" value="'.$langArray[$i][1].'"></td>
                </tr>';
            }
            echo '
            </table>
            <input type="hidden" name="form_key" value="'.$block->getFormKey().'" />
            <input type="hidden" name="lang_file" value="'.$currentFile.'" />
            </form>';
        }
    }
    // .csv file list layout
    else {
        echo '
        <table>
            <tr>
                <th class="post-name">Name</th>
                <th class="post-edit">Content</th>
               </tr>
            <tr>';
        foreach ($languageFiles as $language){
            echo '
                <td>'.$language.'</td>
                <td>
                    <form method="post" action="">
                        <input type="hidden" name="lang_file" value="'.$language.'">
                        <input type="hidden" name="form_key" value="'.$block->getFormKey().'" />
                        <input type="submit" value="Edit">
                    </form>
                    <!-- <a href=\'?file='.$language.'\'><button>Edit</button> </a> -->
                </td>
            </tr>';
        }
        echo '</table>';
    }
    ?>
</body>
</html>
