<?php
/**
 * @var \Solteq\TranslationManagement\Block\Index $block
 */
$languageFiles = $block->findLanguageFiles();
$currentFile = $block->getCurrentFile();
?>
<style>
    <?= include 'css/translations.css'; ?>
</style>

<script>
    require(['jquery', 'jquery/ui'], function($){
        $( document ).ready(function() {

            //wait until the last element (.payment-method) being rendered
            var existCondition = setInterval(function() {
                if ($('.modal-component').length) {
                    clearInterval(existCondition);
                    runMyFunction();
                }
            }, 100);

            function runMyFunction(){
                console.log("Last");
            }

        });
    });
</script>

<div class="page-main-actions sticky">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Edit translations">
            Selected language:
            <form method="post" action="" class="file-selector">
                <select name="lang_file" onchange="this.form.submit()">
                    <option value="">
                        <?php if ($currentFile != ""): ?>
                            <?= $block->languageFileToName($currentFile) ?>
                        <?php else : ?>
                            <?= 'Select a language' ?>
                        <?php endif ?>
                    </option>
                    <?php foreach ($languageFiles as $language) : ?>
                        <option value="<?= $language ?>"> <?= $block->languageFileToName($language) ?> </option>
                    <?php endforeach; ?>
                </select>
                <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
            </form>
            <div class="page-actions-buttons">
                <button value="langTable" id="load_database" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Load from Database" type="submit" form="load-database" data-ui-id="attribute-edit-content-save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text"> Load from database </span>
                </button>
                <button id="save" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Save Attribute" type="submit" form="save-edit" data-ui-id="attribute-edit-content-save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text"> Save </span>
                </button>
                <button value="langTable" id="new_line" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="New Line" type="submit" form="new-line" data-ui-id="attribute-edit-content-save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text"> New Line </span>
                </button>
            </div>
        </div>
    </div>
</div>
<?php if ($currentFile) : ?>
    <?php $langArray = $block->openLanguageFile($currentFile) ?>
    <?php if ($langArray !== 'error') : ?>
<form id="new-line" method="post" action="">
    <input type="hidden" name="new_line" value="Add" />
    <input type="hidden" name="lang_file" value="<?= $currentFile ?>" />
    <input type="hidden" name="form_key" value="<?= $block->getFormKey()?>" />
</form>

<form id="delete-line" method="post" action="">
    <input type="hidden" name="lang_file" value="<?= $currentFile ?>" />
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
</form>

<form id="load-database" method="post" action="">
    <input type="hidden" name="load_database" value="Load" />
    <input type="hidden" name="lang_file" value="<?= $currentFile ?>" />
    <input type="hidden" name="form_key" value="<?= $block->getFormKey()?>" />
</form>

<table id="editable_table">
    <tr>
        <th>String</th>
        <th>Translation</th>
        <th class="delete-col"></th>
    </tr>
        <form id="save-edit" method="post" action="">
            <?php for ($i=0;$i<count($langArray);$i++) : ?>
                <tr>
                    <td>
                        <input class="csv-field" type="text" name="editedArray[<?= $i ?>][0]" value="<?= htmlentities($langArray[$i][0]) ?>">
                    </td>
                    <td>
                        <input class="csv-field" type="text" name="editedArray[<?= $i ?>][1]" value="<?= htmlentities($langArray[$i][1]) ?>">
                        <?php if(isset($langArray[$i][2])) : ?>
                            <input type="hidden" name="editedArray[<?= $i ?>][2]" value="<?= $langArray[$i][2] ?>">
                        <?php endif; ?>
                        <?php if(isset($langArray[$i][3])) : ?>
                            <input type="hidden" name="editedArray[<?= $i ?>][3]" value="<?= $langArray[$i][3] ?>">
                        <?php endif; ?>
                    </td>
                    <td>
                        <button class="delete-button" title="Click to delete line" type="submit" name="delete_line" form="delete-line" value="<?= $i ?>">
                            &#128465;
                        </button>
                    </td>
                </tr>
            <?php endfor; ?>
            <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
            <input type="hidden" name="lang_file" value="<?= $currentFile ?>" />
        </form>
    </table>
    <?php endif; ?>
<?php endif; ?>